-- DATABASE: CHURCHEVENTS
CREATE DATABASE IF NOT EXISTS churchevents
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE churchevents;

-- SESSION SETTINGS
SET sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET time_zone = '+00:00';

-- TABLE: ROLES
DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  name VARCHAR(40) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO roles (id, name) VALUES
  (1, 'Admin'),
  (2, 'Organizer'),
  (3, 'Volunteer')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- TABLE: USERS
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role_id TINYINT UNSIGNED NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- NOTE: USERS SHOULD BE CREATED THROUGH THE APPLICATION TO ENSURE PASSWORDS ARE HASHED.

-- TABLE: CHURCHES
DROP TABLE IF EXISTS churches;
CREATE TABLE churches (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  address1 VARCHAR(160) DEFAULT NULL,
  address2 VARCHAR(160) DEFAULT NULL,
  city VARCHAR(120) NOT NULL,
  state CHAR(2) NOT NULL,
  postal_code VARCHAR(20) DEFAULT NULL,
  phone VARCHAR(40) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_churches_name_city UNIQUE (name, city)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TABLE: EVENTS
DROP TABLE IF EXISTS events;
CREATE TABLE events (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  church_id INT UNSIGNED NOT NULL,
  organizer_id INT UNSIGNED DEFAULT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT DEFAULT NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NOT NULL,
  location VARCHAR(200) DEFAULT NULL,
  capacity INT UNSIGNED DEFAULT NULL,
  status ENUM('draft','published','cancelled') NOT NULL DEFAULT 'published',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_events_church FOREIGN KEY (church_id) REFERENCES churches(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_events_organizer FOREIGN KEY (organizer_id) REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  INDEX idx_events_church (church_id),
  INDEX idx_events_starts (starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TABLE: VOLUNTEER_SIGNUPS
DROP TABLE IF EXISTS volunteer_signups;
CREATE TABLE volunteer_signups (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  signed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_signups_event FOREIGN KEY (event_id) REFERENCES events(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_signups_user FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT uq_event_user UNIQUE (event_id, user_id),
  INDEX idx_signups_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- NOTES
-- USERS ARE NOT SEEDED TO AVOID STORING PASSWORDS IN SQL.
-- CREATE INITIAL ACCOUNTS THROUGH THE APPLICATION'S REGISTRATION SYSTEM.
